"""
app/services/dns_filter.py

Builds dnsmasq-filtered domains file.

Merged sources:
- global blocked_domains
- active group domains

Important:
- service domains are NOT written here anymore.
- service rules are selective and are enforced by app.services.service_enforcer
  using per-device destination-IP blocking.
"""

import subprocess
from flask import current_app

from app.db import get_db
from app.services.firewall import sh


def sanitize_domain(domain: str) -> str:
    import re
    domain = domain.strip().lower()
    if not re.fullmatch(r"[a-z0-9.-]+", domain):
        raise ValueError("Invalid domain format")
    if ".." in domain or domain.startswith(".") or domain.endswith("."):
        raise ValueError("Invalid domain format")
    return domain


def rebuild_domains_file_from_db():
    conn = get_db()
    cur = conn.cursor()

    cur.execute("SELECT domain FROM blocked_domains WHERE enabled=1")
    domains = {r["domain"] for r in cur.fetchall()}

    cur.execute(
        """
        SELECT gd.domain
        FROM group_domains gd
        JOIN groups g ON g.id = gd.group_id
        JOIN active_groups ag ON ag.group_id = gd.group_id
        WHERE ag.active=1 AND gd.enabled=1
        """
    )
    for r in cur.fetchall():
        domains.add(r["domain"])

    conn.close()

    domains = sorted(domains)

    lines = ["# Auto-generated by Smart Firewall backend"]
    for d in domains:
        lines.append(f"address=/{d}/0.0.0.0")
        lines.append(f"address=/www.{d}/0.0.0.0")
    content = "\n".join(lines) + "\n"

    domains_file = current_app.config["DOMAINS_FILE"]
    dns_service = current_app.config["FILTERED_DNS_SERVICE"]

    p = subprocess.run(["sudo", "tee", domains_file], input=content, text=True, capture_output=True)
    if p.returncode != 0:
        raise RuntimeError(p.stderr.strip() or "Failed to write domains file")

    rc, out, err = sh(["sudo", "systemctl", "restart", dns_service])
    if rc != 0:
        raise RuntimeError(err or out or "Failed to restart dnsmasq-filtered")
